<a href="https://colab.research.google.com/github/edenlum/projecteuler/blob/main/15_Lattice_Paths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://projecteuler.net/problem=15

<p>Starting in the top left corner of a $2 \times 2$ grid, and only being able to move to the right and down, there are exactly $6$ routes to the bottom right corner.</p>
<div class="center">
<img src="resources/images/0015.png?1678992052" class="dark_img" alt=""></div>
<p>How many such routes are there through a $20 \times 20$ grid?</p>

In [23]:
# the number of paths from a point is equal to the sum of the number of paths from the points right and down from it.
import numpy as np

n = 8
# we pad with zeros, and an nxn grid has n+1 points (so together with padding its n+2)
grid = np.zeros((n+2, n+2), dtype=int)
grid[n, n] = 1

# going over diagonals
for s in range((n)*2-1, -1, -1):
    for row in range(s - min(n, s), min(n, s) + 1):
        col = s - row
        grid[row, col] = grid[row+1, col] + grid[row, col+1]

print(grid)

[[12870  6435  3003  1287   495   165    45     9     1     0]
 [ 6435  3432  1716   792   330   120    36     8     1     0]
 [ 3003  1716   924   462   210    84    28     7     1     0]
 [ 1287   792   462   252   126    56    21     6     1     0]
 [  495   330   210   126    70    35    15     5     1     0]
 [  165   120    84    56    35    20    10     4     1     0]
 [   45    36    28    21    15    10     6     3     1     0]
 [    9     8     7     6     5     4     3     2     1     0]
 [    1     1     1     1     1     1     1     1     1     0]
 [    0     0     0     0     0     0     0     0     0     0]]
